manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Prospector ZMK Module Remote
    - name: carrefinho                            
      url-base: https://github.com/carrefinho
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # Prospector ZMK Module
    - name: prospector-zmk-Module
      remote: carrefinho
      revision: core/zephyr-4-1
  self:
    path: config