manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Prospector ZMK Module Remote
    - name: carrefinho                            
      url-base: https://github.com/carrefinho
    - name: j1n6                            
      url-base: https://github.com/j1n6
    # Dongle Screen
    - name: janpfischer
      url-base: https://github.com/janpfischer
    - name: bwshockley
      url-base: https://github.com/bwshockley
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # Prospector ZMK Module
    - name: prospector-zmk-Module
      remote: j1n6
      revision: core/zephyr-4-1
  self:
    path: config
